rootProject.name = 'xnat-monorepo'

// Foundation
include 'parent'
include 'test'
include 'framework'
include 'transaction'
include 'extattr'

// Services
include 'prefs'
include 'mail'
include 'config'

// DICOM Tools
include 'dicomtools'
include 'mizer'

// Upper Services
include 'notify'
include 'automation'
include 'dicom-image-utils'
include 'xdat'
include 'spawner'

// dicom-xnat
include 'dicom-xnat-sop'
include 'dicom-xnat-util'

// ANTLR Modules
include 'dicom-edit4'
include 'dicom-edit6'

// Web Application
include 'xnat-web'

// Build plugin (for external XNAT plugins)
include 'xnat-data-builder'
