plugins {
    id 'buildlogic.java-library-conventions'
}

group = 'org.nrg.dicom'

dependencies {
    api project(':framework')
    api project(':transaction')

    api libs.dcm4che5.dcm4che.core
    api libs.dcm4che5.dcm4che.imageio
    implementation libs.spring.orm
    implementation libs.spring.context
    implementation libs.commons.codec
    implementation libs.google.guava
    api libs.uuid.java.uuid.generator
    implementation libs.slf4j.api
    implementation libs.slf4j.log4j12

    compileOnly libs.google.jsr305

    testImplementation project(':test')
    testImplementation variantOf(libs.ehcache.ehcache) { classifier('jakarta') }
    testImplementation libs.junit.junit
    testImplementation libs.spring.test
}
