plugins {
    id 'buildlogic.java-library-conventions'
}

dependencies {
    api libs.dcm4che5.dcm4che.core
    api libs.dcm4che5.dcm4che.dict
    api libs.google.guava

    implementation libs.commons.lang3
    implementation libs.commons.io
    implementation libs.slf4j.api


    testImplementation libs.slf4j.simple
    testImplementation libs.junit.junit
}
