public:
  - buildInfo
  - siteHome
  - siteId
  - siteLogoPath
  - siteUrl

authenticated:
  - checksums
  - defaultProjectAutoArchiveSetting
  - dicomFileNameTemplate
  - displayHostName
  - enableDicomReceiver
  - enableSitewideAnonymizationScript
  - enableSitewideSeriesImportFilter
  - failMergeOn
  - processingUrl
  - projectAllowAutoArchive
  - scanTypeMapping
  - sessionXmlRebuilderInterval
  - sessionXmlRebuilderRepeat
  - siteDescriptionPage
  - siteDescriptionText
  - siteDescriptionType
  - siteHomeLayout
  - siteLandingLayout
  - siteLoginLanding
  - siteWideAlertMessage
  - siteWideAlertStatus
  - siteWideAlertType
  - sitewideAnonymizationScript
  - sitewidePetMr
  - sitewidePetTracers
  - sitewideSeriesImportFilter
  - sitewideSeriesImportFilterMode
  - uiAllowAdvancedSearch
  - uiAllowBlockedSubjectAssessorView
  - uiAllowMoreProjectInvestigators
  - uiAllowNewUserComments
  - uiAllowNonAdminProjectCreation
  - uiAllowPetTracerConfiguration
  - uiAllowProjectDelete
  - uiAllowQuarantine
  - uiAllowScanAddition
  - uiAllowScanTypeModification
  - uiAllowSubjectCreateFromExptEdit
  - uiDateFormat
  - uiDateTimeFormat
  - uiDateTimeSecondsFormat
  - uiDebugExtensionPoints
  - uiDisplayScanModality
  - uiDisplaySeriesClass
  - uiDisplaySeriesDescription
  - uiExptAllowLabelChange
  - uiExptAllowProjectChange
  - uiExptAllowSubjectChange
  - uiHideCompressedUploaderUploadOption
  - uiDefaultCompressedUploaderImporter
  - uiHideDesktopClientDownload
  - uiHideXnatUploadAssistantDownload
  - uiLoginFailureMessage
  - uiPrearchiveHideArchiveBtn
  - uiShowLeftBar
  - uiShowLeftBarBrowse
  - uiShowLeftBarFavorites
  - uiShowLeftBarProjects
  - uiShowLeftBarSearch
  - uiShowManageFiles
  - uiShowPrearchiveFileActions
  - uiShowProjectManageFiles
  - uiShowRecentExptListDate
  - uiShowRecentExptListScannerName
  - uiShowScanTypeMapping
  - uiTimeFormat
  - zipExtensions

admin:
  - adminEmail
  - aliasTokenTimeout
  - aliasTokenTimeoutSchedule
  - allowDataAdmins
  - allowHtmlResourceRendering
  - allowNonAdminsToClaimUnassignedSessions
  - archivePath
  - backupDeletedToCache
  - buildPath
  - cachePath
  - canResetFailedLoginsWithForgotPassword
  - concurrentMaxSessions
  - csrfEmailAlert
  - dataPaths
  - emailProjectAccessRequestToAdmin
  - emailVerification
  - emailVerificationMessage
  - enableCsrfToken
  - enableDicomReceiverPropertyChangedListener
  - enabledProviders
  - featureRepositoryService
  - featureService
  - ftpPath
  - imageSessionDisplayNamePlural
  - imageSessionDisplayNameSingular
  - inactivityBeforeLockout
  - inactivityBeforeLockoutSchedule
  - inboxPath
  - initialized
  - interactiveAgentIds
  - ipsThatCanSendEmailsThroughRest
  - maintainFileHistory
  - matchSecurityProtocol
  - maxFailedLogins
  - maxFailedLoginsLockoutDuration
  - maxNumberOfSessionsForJobsWithSharedData
  - par
  - passwordComplexity
  - passwordComplexityMessage
  - passwordExpirationDate
  - passwordExpirationInterval
  - passwordExpirationType
  - passwordHistoryDuration
  - passwordReuseRestriction
  - pathErrorWarning
  - pipelinePath
  - prearchivePath
  - preventCrossModalityMerge
  - primaryAdminUsername
  - receivedFileUser
  - reloadPrearcDatabaseOnStartup
  - requireChangeJustification
  - requireEventName
  - requireImageAssessorLabels
  - requireLogin
  - resetFailedLoginsSchedule
  - restrictUserListAccessToAdmins
  - roleRepositoryService
  - roleService
  - securityAllowNonPrivateProjects
  - securityChannel
  - securityExternalUserParDisabled
  - securityLastModifiedInterval
  - securityMaxLoginInterval
  - securityNewUserRegistrationDisabled
  - sessionArchiveTimeoutInterval
  - sessionTimeout
  - sessionTimeoutMessage
  - showChangeJustification
  - userRegistration