plugins {
    id 'buildlogic.java-library-conventions'
    id 'groovy'
}

group = 'org.nrg.xnat'

dependencies {
    api(project(':xdat')) { transitive = false }
    api(project(':framework')) { transitive = false }
    api(project(':config')) {
        exclude group: 'xml-apis', module: 'xml-apis'
    }

    implementation libs.spring.webmvc
    implementation libs.spring.security.spring.security.core
    implementation libs.springfox.swagger2
    implementation libs.springfox.swagger.ui
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml
    implementation libs.jackson.dataformat.xml
    implementation libs.postgresql.postgresql
    implementation libs.groovy.all
    compileOnly libs.servlet.javax.servlet.api


    testImplementation libs.servlet.javax.servlet.api
    testImplementation project(':test')
    testImplementation libs.junit.junit
    testImplementation libs.spring.test
    testImplementation libs.assertj.core
    testImplementation libs.hamcrest.library
    testImplementation libs.h2database.h2
}
