plugins {
    id 'buildlogic.java-library-conventions'
    id 'antlr'
}

group = 'org.nrg.dicom'

sourceSets {
    main {
        antlr {
            srcDirs = ['src/main/antlr3']
        }
        resources {
            srcDirs += ['src/main/dicomedit']
        }
    }
}

dependencies {
    antlr libs.antlr.antlr
    api libs.antlr.runtime

    api project(':mizer')
    api project(':dicomtools')
    api(project(':framework')) { transitive = false }

    api libs.google.guava
    api libs.json.json
    api libs.reflections.reflections
    api libs.slf4j.api

    compileOnly(libs.spring.web) { transitive = false }
    compileOnly libs.google.jsr305
    compileOnly libs.metainf.services.metainf.services
    annotationProcessor libs.metainf.services.metainf.services

    testImplementation project(':test')
    testImplementation libs.junit.junit
    testImplementation libs.spring.test
    testImplementation libs.easymock.easymock
    testRuntimeOnly libs.slf4j.simple


    // DE4FAnnotationProcessor must process @DicomEdit4Function on test classes
    testAnnotationProcessor files(sourceSets.main.output)
    testAnnotationProcessor project(':framework')
    testAnnotationProcessor libs.metainf.services.metainf.services
    testAnnotationProcessor libs.commons.lang3
}
